apiVersion: webapp.example.com/v1
kind: GuestBook
metadata:
  name: guestbook-sample
spec:
  redisName: redis-sample
  frontend:
    resources:
      requests:
        cpu: 80m
    # check that this doesn't work,
    # then delete it
    servingPort: 8080
